// This file is generated by icon spritesheet generator

export const iconNames = [
  "wifi",
  "wifi-off",
  "sun",
  "search",
  "refresh",
  "pencil",
  "moon",
  "info",
  "download",
  "copy",
  "copy-check",
  "cog",
  "codesandbox",
  "code",
  "bookmark",
] as const

export type IconName = typeof iconNames[number]
