// This file is generated by icon spritesheet generator

export const iconNames = [
  "sun",
  "search",
  "refresh",
  "moon",
  "cog",
  "codesandbox",
  "code",
] as const

export type IconName = typeof iconNames[number]
