name: Release

on:
  push:
    branches: [main, dev]

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Needs to fetch historical commits in order to compare with origin/main
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Sync sandbox
        run: npm run preinstall -w @remix-pwa/playground
      - name: Install dependencies
        run: npm clean-install
      - name: Build packages
        run: npm run build
      - name: Setup NPM
        run: |
          npm config set workspaces-update=false --global
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
          HUSKY: 0
        run: |
          npx --package @semantic-release/release-notes-generator --package @semantic-release/git --package @semantic-release/changelog --package @qiwi/multi-semantic-release multi-semantic-release
